# GitHub Action para gerar o gráfico de contribuições da snake

name: Generate Snake

on:
  schedule:
    # Roda a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: danielriegoor
          # Lista de saídas que serão geradas
          # gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
